# Generated by Django 5.1.5 on 2025-02-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customuser_alter_event_rsvp_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rsvp_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
